name: Activate poetry
description: Install and activate poetry virtual environment
runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        

    - name: Create venv
      shell: bash
      run: |
        poetry install --no-root